# Generated by Django 5.0.6 on 2024-08-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBankModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='Enter the full question text here. Be descriptive.')),
                ('option_a', models.CharField(help_text='Provide Option (A)', max_length=250)),
                ('option_b', models.CharField(help_text='Provide Option (B)', max_length=250)),
                ('option_c', models.CharField(help_text='Provide Option (C)', max_length=250)),
                ('correct_answer', models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C')], help_text='Select the correct answer option (A, B or C).', max_length=1)),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
        ),
    ]
