# Generated by Django 5.0.6 on 2024-08-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('duration', models.PositiveIntegerField()),
                ('questions', models.ManyToManyField(blank=True, related_name='Quizzes', to='quiz_backend.questionbankmodel')),
            ],
        ),
    ]
