# Generated by Django 5.0.6 on 2024-08-21 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_backend', '0004_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
