# Generated by Django 5.0.6 on 2024-08-21 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_backend', '0005_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionbankmodel',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='quiz_backend.category'),
        ),
    ]
