# Generated by Django 5.0.6 on 2024-08-29 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_backend', '0006_questionbankmodel_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category_name', models.CharField(max_length=250)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='quiz_backend.category')),
            ],
            options={
                'verbose_name_plural': 'SubCategories',
                'unique_together': {('category', 'sub_category_name')},
            },
        ),
    ]
