# Generated by Django 5.0.6 on 2024-08-30 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_backend', '0007_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionbankmodel',
            name='sub_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='quiz_backend.subcategory'),
        ),
    ]
